### PR TITLE
Add 3DFillies to logos.ts

### PR DESCRIPTION
**Pull request by ghost**
3DFillies is an Australian based filament supplier, where I buy my filament from.

### CODE REVIEW

**Comment by BrianGilbert** [comment]
Example of output:
Bambu LabelGen 2024-04-09 15-59-33

**Comment by ItsVRK** [comment]
Example of output:

Bambu LabelGen 2024-04-09 15-59-33

**Comment by SoCuul** [comment]
Hey, thanks for contributing!

Would it be possible for you to scale down the logo slightly? I've attempted to make each logo fit the height of the Bambu logo option.

Also if you could bump the version in package.json that'd be super helpful 👍

**Comment by ItsVRK** [comment]
> Hey, thanks for contributing!
> 
> Would it be possible for you to scale down the logo slightly? I've attempted to make each logo fit the height of the Bambu logo option.
> 
> Also if you could bump the version in package.json that'd be super helpful 👍

Sure, give me a few minutes

**Comment by ItsVRK** [comment]
@SoCuul updated..

Bambu LabelGen 2024-04-09 16-13-23

**Comment by ItsVRK** [comment]
oh wait, I need to adjust it's location.. too high now

**Comment by ItsVRK** [comment]
@SoCuul fixed, ready to merge if you're happy

**Comment by SoCuul** [comment]
LGTM 👍

**Pull request merged**
